spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chess_mate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234

application:
  name: ChessMate

lichess:
  base-url: https://lichess.org
  client-id: abc123def456
  redirect-url: http://localhost:3000/callback
  ttl:
    account: 3600 # 유저 정보 캐시 1시간
