spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: localhost
      port: 6379
      key:
        account_key: LICHESSA_ACCOUNT
        oauth_key: LICHESS_OAUTH
        perf_key: LICHESS_PERF
        games_key: LICHESS_GAMES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chess_mate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jwt:
    access-token:
        secret: chessMateGbswProjectAccessTokenSecret
        expiration: 36000000000000 # 1 시간
    refresh-token:
        secret: chessMateGbswProjectRefreshTokenSecret
        expiration: 6048000000000 # 7 일

application:
  name: ChessMate

lichess:
  base-url: https://lichess.org
  client-id: abc123def456
  redirect-url: http://localhost:3000/callback
  ttl:
    account: 3600 # 유저 정보 캐시 1시간
